// TOP 250 Anime

module.exports = [
  "Your Name",
  "Fullmetal Alchemist: Brotherhood",
  "Steins; Gate",
  "Clannad After Story",
  "Rurouni Kenshin: Trust & Betrayal",
  "Code Geass: Lelouch of the Rebellion R2",
  "Spirited Away",
  "A Silent Voice",
  "Cowboy Bebop",
  "Mushishi: The Next Chapter",
  "Princess Mononoke",
  "The Disappearance of Haruhi Suzumiya",
  "The Legend of the Galactic Heroes",
  "Mushi-Shi",
  "Death Note",
  "Made in Abyss",
  "Maria Watches Over Us 3rd Season",
  "Maria Watches Over Us Season 2: Printemps",
  "Descending Stories: Showa Genroku Rakugo Shinju",
  "Anohana: The Flower We Saw That Day",
  "Code Geass: Lelouch of the Rebellion",
  "Gintama' 2011",
  "Maria Watches Over Us 4th Season",
  "Gintama' 2012",
  "Gintama' 2015",
  "Bunny Drop",
  "Evangelion: 2.0 You Can (Not) Advance",
  "Monster",
  "Grave of the Fireflies",
  "Cross Game",
  "Ghost in the Shell: Stand Alone Complex 2nd GIG",
  "Summer Wars",
  "Fighting Spirit",
  "Hunter x Hunter (2011)",
  "Fullmetal Alchemist",
  "Nodame Cantabile",
  "The Girl Who Leapt Through Time",
  "5 Centimeters Per Second",
  "Nausicaä of the Valley of the Wind",
  "Gurren Lagann",
  "The Garden of Sinners",
  "Wolf Children",
  "My Neighbor Totoro",
  "Baccano!",
  "Gekijōban Gintama Kanketsu-hen: Yorozuya yo Eien Nare",
  "Natsume's Book of Friends 4",
  "Honey and Clover II",
  "Star Blazers 2199",
  "Hajime no Ippo: New Challenger",
  "Kanon 2006",
  "GTO: Great Teacher Onizuka",
  "Kino's Journey",
  "Time of Eve",
  "Howl's Moving Castle",
  "Puella Magi Madoka Magica",
  "Mushishi Tokubetsu-hen: Hihamukage",
  "Time of Eve (movie)",
  "Natsume's Book of Friends 2",
  "Monogatari Series Second Season",
  "Millennium Actress",
  "Kaleido Star",
  "Natsume's Book of Friends 3",
  "Kids on the Slope",
  "Mononoke",
  "The Melancholy of Haruhi Suzumiya",
  "Gankutsuou: The Count of Monte Cristo",
  "Clannad",
  "Planetes",
  "NANA",
  "Looking Up At The Half-Moon",
  "Castle in the Sky",
  "Whisper of the Heart",
  "Your Lie in April",
  "March comes in like a lion 2",
  "Ouran High School Host Club",
  "Samurai Champloo",
  "Gurren Lagann the Movie – The Lights in the Sky Are Stars",
  "The Beast Player Erin",
  "A Place Further Than the Universe",
  "Ghost in the Shell: Stand Alone Complex",
  "Maria Watches Over Us",
  "Aria the Origination",
  "Angel Beats!",
  "Spice and Wolf II",
  "Moribito - Guardian of the Spirit",
  "Haikyu!! Second Season",
  "Re:ZERO -Starting Life in Another World",
  "ef: a tale of melodies",
  "ef: a tale of memories",
  "Haikyu!! 3rd Season",
  "Black Lagoon: The Second Barrage",
  "Welcome to the NHK",
  "Legend of the Galactic Heroes: Overture to a New War",
  "My Hero Academia Season 2",
  "Mushishi: Zoku-Shō: Suzu no Shizuku",
  "Honey and Clover",
  "Sword of the Stranger",
  "Haibane Renmei",
  "The Tale of the Princess Kaguya",
  "The Twelve Kingdoms",
  "Hunter x Hunter (OAV)",
  "Cowboy Bebop: The Movie",
  "Toradora!",
  "Tokyo Godfathers",
  "Romeo × Juliet",
  "Major",
  "Evangelion: 1.0 You Are (Not) Alone",
  "Maison Ikkoku",
  "Hellsing Ultimate",
  "Katanagatari",
  "Chihayafuru",
  "Shirobako",
  "Tsubasa Tokyo Revelations",
  "The Garden of Words",
  "Owarimonogatari",
  "Mobile Suit Gundam UC",
  "Full Metal Panic! The Second Raid",
  "Hunter X Hunter (TV)",
  "Gintama. 2017",
  "Fate/Zero 2nd",
  "ERASED",
  "BECK: Mongolian Chop Squad",
  "Kimi ni Todoke - From Me to You",
  "My Hero Academia Season 3",
  "La Maison en Petits Cubes",
  "Den-noh Coil",
  "Attack on Titan Season 2",
  "One Piece Episode of Nami: Kōkaishi no Namida to Nakama no Kizuna",
  "Bakuman. 2",
  "Natsume's Book of Friends",
  "Nodame Cantabile: Paris",
  "Berserk",
  "Brave King GaoGaiGar Final",
  "JoJo's Bizarre Adventure: Diamond Is Unbreakable",
  "Kaiba",
  "Ashita no Joe 2",
  "Ping Pong",
  "Princess Tutu",
  "Conan, the Boy in Future",
  "Natsume Yūjin-Chō Roku 6",
  "Hotarubi no Mori e",
  "Azumanga Daioh",
  "Maquia - When the Promised Flower Blooms",
  "Full Metal Panic? Fumoffu",
  "Eden of the East",
  "Nodame Cantabile: Finale",
  "Haikyu!!",
  "Mushishi Zoku-Shō Tokubetsu-hen: Odoro no Michi",
  "The Rose of Versailles",
  "Hunter X Hunter: G I Final",
  "Yuri!! on Ice",
  "Berserk: The Golden Age Arc III - The Advent",
  "Violet Evergarden",
  "Kimi ni Todoke 2nd Season",
  "Girls und Panzer der Film",
  "Assassination Classroom",
  "Mob Psycho 100",
  "Trigun",
  "Hanasaku Iroha - Blossoms for Tomorrow",
  "Ghost in the Shell: Stand Alone Complex: Solid State Society",
  "Paprika",
  "Spice and Wolf",
  "School Rumble: 2nd Semester",
  "Magnetic Rose",
  "R.O.D -The TV-",
  "Sound! Euphonium 2",
  "Land of the Lustrous",
  "Gungrave",
  "Last Exile",
  "The Eccentric Family 2",
  "Rurouni Kenshin",
  "Legend of the Galactic Heroes: My Conquest is the Sea of Stars",
  "Bakuman. 3",
  "Comedy",
  "When Marnie Was There",
  "Natsume Yūjin-Chō Go",
  "Skip Beat",
  "xxxHOLiC: Kei",
  "Bakemonogatari",
  "Attack on Titan",
  "Neon Genesis Evangelion: The End of Evangelion",
  "The Super Dimension Fortress Macross: Do You Remember Love?",
  "Master Keaton",
  "Kiki's Delivery Service",
  "Hunter X Hunter: Greed Island",
  "Romeo and the Black Brothers",
  "In This Corner of the World",
  "Hajime no Ippo - Champion Road",
  "Gintama",
  "The Super Dimension Fortress Macross",
  "Tiger &amp; Bunny",
  "Fate/stay night: Unlimited Blade Works",
  "Black Lagoon",
  "Neon Genesis Evangelion",
  "One Outs",
  "Ghost in the Shell: Stand Alone Complex - Individual Eleven",
  "The Anthem of the Heart",
  "Food Wars! Shokugeki no Soma",
  "Hinamatsuri",
  "The Boy and The Beast",
  "Fate/Zero",
  "Macross Frontier",
  "No Game, No Life Zero",
  "Darker than Black",
  "Mobile Suit Gundam 00 Second Season",
  "Space Brothers",
  "Gosick",
  "Nichijou - My Ordinary Life",
  "Monthly Girls' Nozaki-kun",
  "Denpa teki na Kanojo",
  "Lupin III: The Castle of Cagliostro",
  "Welcome to THE SPACE SHOW",
  "Aria the Avvenire",
  "One Punch Man",
  "Elfen Lied",
  "Emma: A Victorian Romance Second Act",
  "Nobody's Boy Remi",
  "Wolf's Rain",
  "My Hero Academia",
  "Rainbow - Nisha Rokubō no Shichinin",
  "Junjō Romantica 2",
  "Ghost in the Shell: Stand Alone Complex - The Laughing Man",
  "No Game, No Life",
  "Magical Girl Lyrical Nanoha the Movie 2nd A's",
  "Eureka Seven",
  "Tokyo Magnitude 8.0",
  "Kill la Kiil",
  "School Rumble",
  "Parasyte -the maxim-",
  "Kizumonogatari Part 1: Tekketsu",
  "Kizumonogatari Part 3: Reiketsu",
  "Ghost in the Shell",
  "Now and Then, Here and There",
  "Wagnaria!!3",
  "Berserk: The Golden Age Arc II - The Battle for Doldrey",
  "Kizumonogatari Part 2: Nekketsu",
  "Puella Magi Madoka Magica the Movie Part 2: Eternal",
  "planetarian: Hoshi no Hito",
  "Puella Magi Madoka Magica the Movie Part 1: Beginnings",
  "Porco Rosso",
  "Kimagure Orange Road: The Movie",
  "Lovely Complex",
  "The Place Promised in Our Early Days",
  "Hikaru No Go: New Year Special",
  "Hajime no Ippo - Mashiba vs. Kimura",
  "Cardcaptor Sakura Movie 2: The Sealed Card",
  "Legend of the Galactic Heroes: A Hundred Billion Stars, A Hundred Billion Lights",
  "Detroit Metal City",
  "The Wind Rises",
  "Mobile Suit Gundam - The Movie Trilogy"
];